import type { Metadata } from "next";
import { Anonymous_Pro, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './reset.css'
import Providers from "./Providers";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anonymousPro = Anonymous_Pro({
  variable: "--font-anonymous-pro",
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://telegram.org/js/telegram-web-app.js?59"
        />
          
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${anonymousPro.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
